### ISSUE TITLE
Chimp test mini game

### ISSUE THREAD

**Issue by shinramenisbae** [SOFTENG310-G5/BrainSomething#11]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem.

**Describe the solution you'd like**
I believe we should implement a chimp test mini game as per our project proposal. 

**Describe alternatives you've considered**
None

**Additional context**
The logic should be implemented in the pages directory in js and import some components from the react library as well some custom ones

**Comment by ThisukaM** [comment]
This issue was completed in [28](https://github.com/SOFTENG310-G5/BrainSomething/pull/28)
