### ISSUE TITLE
Leaderboard feature

### ISSUE THREAD

**Issue by shinramenisbae** [SOFTENG310-G5/BrainSomething#12]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
We should implement a leaderboard system that shows the user how well they've done against other users.

**Describe alternatives you've considered**

**Additional context**

**Comment by ThisukaM** [comment]
Added in [#35](https://github.com/SOFTENG310-G5/BrainSomething/pull/35)
